Repository EZ-Robotics/EZ-Template, pull requests merged in 2025-09, with the labels that each got.

#273 ✨Add an optional parameter for running the loading bar
  include/EZ-Template/drive/drive.hpp
  src/EZ-Template/drive/drive.cpp
Labels: enhancement

#253 :bug: One function for adding PIDs to tuner
  include/EZ-Template/drive/drive.hpp
  src/EZ-Template/drive/pid_tuner.cpp
Labels: enhancement

#284 Uses central pose for two vert trackers
  src/EZ-Template/drive/tracking.cpp
  src/main.cpp
Labels: bug, enhancement

#247 ✨Tracking is now an std::function
  include/EZ-Template/drive/drive.hpp
  src/EZ-Template/drive/drive.cpp
  src/EZ-Template/drive/tracking.cpp
Labels: enhancement

#294 🐛 Bug/namespace
  EZ-Template-Example-Project/include/EZ-Template/drive/drive.hpp
  EZ-Template-Example-Project/include/subsystems.hpp
  EZ-Template-Example-Project/src/autons.cpp
  EZ-Template-Example-Project/src/main.cpp
  include/EZ-Template/drive/drive.hpp
  include/main.h
  include/subsystems.hpp
  src/EZ-Template/PID.cpp
  src/EZ-Template/auton.cpp
  src/EZ-Template/auton_selector.cpp
  src/EZ-Template/drive/pid_tuner.cpp
  src/EZ-Template/drive/pto.cpp
  src/EZ-Template/drive/purepursuit_math.cpp
  src/EZ-Template/drive/set_pid/set_drive_pid.cpp
  src/EZ-Template/drive/set_pid/set_odom_pid.cpp
  src/EZ-Template/drive/set_pid/set_pid.cpp
  src/EZ-Template/drive/set_pid/set_swing_pid.cpp
  src/EZ-Template/drive/set_pid/set_turn_pid.cpp
  src/EZ-Template/drive/tracking.cpp
  src/EZ-Template/drive/user_input.cpp
  src/EZ-Template/piston.cpp
  src/EZ-Template/slew.cpp
  src/EZ-Template/tracking_wheel.cpp
  src/autons.cpp
  src/main.cpp
Labels: restructuring
